#!/usr/bin/env Rscript
# Takes a matrix file generated by rank-mat.r and converts it to a Q-matrix 
# (see Computational Methods paper, http://www.cell.com/action/showImagesData?pii=S0092-8674%2812%2901123-3 ) 
args <- commandArgs(trailingOnly=TRUE)
orig_matpath <- paste0(getwd(), "/", as.character(args[1])) # assumes Unix
ranked_matpath <- paste0(getwd(), "/", as.character(args[2])) # assumes Unix
print(paste("Looking for original matrix at:", orig_matpath))
print(paste("Looking for ranked matrix at:", ranked_matpath))

# check arguments for validity
if(length(args) != 2 || !file.exists(orig_matpath) || !file.exists(ranked_matpath)) {
  print("Incorrect or missing argument. File may not exist.")
  print("Usage: get-q-mat.r <relative original matrix filepath> <relative ranked matrix filepath>")
  stop()
}

convert_q <- function(orig_matpath, ranked_matpath) {
  print("Reading ranked matrix.")
  ranked_mat <- as.data.frame(read.table(ranked_matpath, sep="\t", header=TRUE))
  rownames(ranked_mat) <- ranked_mat[, 1]
  ranked_mat[, 1] <- NULL
  
  print("Reading original matrix.")
  orig_mat <- as.data.frame(read.table(orig_matpath, sep="\t", header=TRUE))
  rownames(orig_mat) <- orig_mat[, 1]
  orig_mat[, 1] <- NULL
  
  print("Calculating sign matrix.")
  sign_mat <- sign(orig_mat)
  
  print("Applying quantile score function over ranked matrix.")
  qmat <- mapply(qscore, ranked_mat, sign_mat, MoreArgs = list(n_nonzero = sum(orig_mat != 0)))
  rownames(qmat) <- rownames(orig_mat)
  
  matname <- strsplit(basename(ranked_matpath), "[.]")
  filename=paste0(dirname(ranked_matpath), "/", matname[[1]][1], "_q.txt")
  print(paste("Writing Q-matrix to file:", filename))
  write.table(qmat, file = filename, sep = "\t", row.names = TRUE, col.names = NA)
}

# convert non-zero confidence score into quantile score that ranges 
# from zero (lowest confidence) to 1 (highest confidence) 
qscore <- function(rank, signval, n_nonzero) {
  (1 - (rank/n_nonzero)) * signval
}

convert_q(orig_matpath, ranked_matpath)