#!/usr/bin/env Rscript
# Takes a matrix file generated by rank-mat.r and converts it to a Q-matrix
# (see Computational Methods paper, http://www.cell.com/action/showImagesData?pii=S0092-8674%2812%2901123-3 ) 
args <- commandArgs(trailingOnly=TRUE)
matpath <- paste0(getwd(), "/", as.character(args[1])) # assumes Unix
print(paste("Looking for matrix at:", matpath))

# regex test for option which may only be a combination of the character set [k,c,r,i] 
if(length(args) != 1 || !file.exists(matpath)) {
  print("Incorrect or missing argument. File may not exist.")
  print("Usage: rank-mat.R <relative matrix filepath>")
  stop()
}