#!/usr/bin/env Rscript
# Takes a matrix file generated by rank-mat.r and converts it to a Q-matrix 
# (see Computational Methods paper, http://www.cell.com/action/showImagesData?pii=S0092-8674%2812%2901123-3 ) 
iopath <- paste0(getwd(), "/../suppl/data/analysis/")
if(!dir.exists(iopath)) {
  dir.create(iopath)
}
setwd(iopath)

ALLOWED_OPTS <- c("chip", "deseq", "rna", "immgen")
args <- commandArgs(trailingOnly=TRUE)

if(length(args) != 1) {
  print("Incorrect or missing argument.")
  print("Usage: qmat_gen.r <data type> [allowed: chip, deseq, rna, immgen]")
  stop("invalid argument number")
}

opt = casefold(as.character(args[1]), upper = FALSE)

if(!opt %in% ALLOWED_OPTS) {
  print("Incorrect option.")
  print("Usage: rank_mat.r <data type> [allowed: chip, deseq, rna, immgen]")
  stop("invalid option")
}

orig_matpath <- getwd() # non-empty default
ranked_matpath <- getwd() # non-empty default
if(opt == "chip") {
  orig_matpath <- paste0(getwd(), "C_Th17_mat.txt")
  ranked_matpath <- paste0(getwd(), "C_Th17_mat_ranked.txt")
  
} else if(opt == "deseq") {
  orig_matpath <- paste0(getwd(), "K_Th17_mat.txt")
  ranked_matpath <- paste0(getwd(), "K_Th17_mat_ranked.txt")
  
} else if(opt == "rna") {
  orig_matpath <- paste0(getwd(), "/../inferelator/", "GSE40918_Inferelator_RNAseq.txt")
  ranked_matpath <- paste0(getwd(), "GSE40918_Inferelator_RNAseq_ranked.txt")
  
} else if(opt == "immgen") {
  orig_matpath <- paste0(getwd(), "/../inferelator/", "GSE40918_Inferelator_Immgen.txt")
  ranked_matpath <- paste0(getwd(), "GSE40918_Inferelator_Immgen_ranked.txt")
  
} else {
  print(paste("Some weird option slipped through the checks:", opt))
  stop("invalid option")
}

print(paste("Looking for matrix at:", orig_matpath))
print(paste("Looking for matrix at:", ranked_matpath))

# check arguments for validity
if(!file.exists(orig_matpath) || !file.exists(ranked_matpath)) {
  print("Incorrect path. Original matrix file (pre-rank) may not exist.")
  print("Usage: rank_mat.r <data type> [allowed: chip, deseq, rna, immgen]")
  stop(paste("File not found at:", matpath))
}

convert_q <- function(orig_matpath, ranked_matpath) {
  print("Reading ranked matrix.")
  ranked_mat <- as.data.frame(read.table(ranked_matpath, sep="\t", header=TRUE))
  rownames(ranked_mat) <- ranked_mat[, 1]
  ranked_mat[, 1] <- NULL
  
  print("Reading original matrix.")
  orig_mat <- as.data.frame(read.table(orig_matpath, sep="\t", header=TRUE))
  rownames(orig_mat) <- orig_mat[, 1]
  orig_mat[, 1] <- NULL
  
  print("Calculating sign matrix.")
  sign_mat <- sign(orig_mat)
  
  print("Applying quantile score function over ranked matrix.")
  qmat <- mapply(qscore, ranked_mat, sign_mat, MoreArgs = list(n_nonzero = sum(orig_mat != 0)))
  rownames(qmat) <- rownames(orig_mat)
  
  matname <- strsplit(basename(ranked_matpath), "[.]")
  
  filename=paste0(getwd(), matname[[1]][1], "_q.txt")
  print(paste("Writing Q-matrix to file:", filename))
  write.table(qmat, file = filename, sep = "\t", row.names = TRUE, col.names = NA)
}

# convert non-zero confidence score into quantile score that ranges 
# from zero (lowest confidence) to 1 (highest confidence) 
qscore <- function(rank, signval, n_nonzero) {
  (1 - (rank/n_nonzero)) * signval
}

convert_q(orig_matpath, ranked_matpath)