#!/usr/bin/env Rscript
# Takes a matrix file generated by generate-chipseq-mat.r and converts it to a rank matrix
args <- commandArgs(trailingOnly=TRUE)
matpath <- paste0(getwd(), "/", as.character(args[1])) # assumes Unix
print(paste("Looking for matrix at:", matpath))

# regex test for option which may only be a combination of the character set [k,c,r,i] 
if(length(args) != 1 || !file.exists(matpath)) {
  print("Incorrect or missing argument. File may not exist.")
  print("Usage: rank-mat.R <relative matrix filepath>")
  stop()
}

# applies rank function to matrix <matname> and writes it into the same directory as the source file
# wrapped in function for possible reuse or automation 
rank_mat <- function(matpath) {
  print("Reading matrix.")
  mat <- as.data.frame(read.table(matpath, sep="\t", header=TRUE))
  rownames(mat) <- mat[, 1]
  mat[, 1] <- NULL
  
  print("Ranking.")
  # replace all zeroes with NA to exclude them from ranking
  mat[mat == 0] <- NA
  # apply rank
  ranked_mat <- matrix(rank(mat, na.last = "keep"), ncol=ncol(mat))
  # replace all NAs with zeroes again post-ranking
  ranked_mat[is.na(ranked_mat)] <- 0
  
  rownames(ranked_mat) <- rownames(mat)
  colnames(ranked_mat) <- colnames(mat)
  
  filename=paste0(matpath, "_ranked.txt")
  print(paste("Writing ranked matrix to file:", filename))
  write.table(ranked_mat, file = filename, sep = "\t", row.names = TRUE, col.names = NA)
}

rank_mat(matpath)
#TODO generate q-matrix and write that instead