#!/usr/bin/env Rscript
# Takes a matrix file generated by generate-chipseq-mat.r and converts it to a rank matrix
# (see Computational Methods paper, http://www.cell.com/action/showImagesData?pii=S0092-8674%2812%2901123-3 ) 
iopath <- paste0(getwd(), "/../suppl/data/analysis/")
if(!dir.exists(iopath)) {
  dir.create(iopath)
}
setwd(iopath)

ALLOWED_OPTS <- c("chip", "deseq", "rna", "immgen")
args <- commandArgs(trailingOnly=TRUE)

if(length(args) != 1) {
  print("Incorrect or missing argument.")
  print("Usage: rank_mat.r <data type> [allowed: chip, deseq, rna, immgen]")
  stop("invalid argument number")
}

opt = casefold(as.character(args[1]), upper = FALSE)

if(!opt %in% ALLOWED_OPTS) {
  print("Incorrect option.")
  print("Usage: rank_mat.r <data type> [allowed: chip, deseq, rna, immgen]")
  stop("invalid option")
}

matpath <- getwd() # non-empty default
if(opt == "chip") {
  matpath <- paste0(getwd(), "C_Th17_mat.txt")
  
} else if(opt == "deseq") {
  matpath <- paste0(getwd(), "K_Th17_mat.txt")
  
} else if(opt == "rna") {
  matpath <- paste0(getwd(), "/../inferelator/", "GSE40918_Inferelator_RNAseq.txt")
  
} else if(opt == "immgen") {
  matpath <- paste0(getwd(), "/../inferelator/", "GSE40918_Inferelator_Immgen.txt")
  
} else {
  print(paste("Some weird option slipped through the checks:", opt))
  stop("invalid option")
}

print(paste("Looking for matrix at:", matpath))

# check arguments for validity
if(!file.exists(matpath)) {
  print("Incorrect path. Original matrix file (pre-rank) may not exist.")
  print("Usage: rank_mat.r <data type> [allowed: chip, deseq, rna, immgen]")
  stop(paste("File not found at:", matpath))
}

# applies rank function to matrix <matname> and writes it into the same directory as the source file
# wrapped in function for possible reuse or automation 
rank_mat <- function(matpath) {
  print("Reading matrix.")
  mat <- as.data.frame(read.table(matpath, sep="\t", header=TRUE))
  rownames(mat) <- mat[, 1]
  mat[, 1] <- NULL
  
  print("Ranking.")
  # replace all zeroes or infinities with NA to exclude them from ranking
  mat[mat == 0] <- NA
  # apply rank to absolute value of confidence scores
  ranked_mat <- matrix(rank(abs(mat), na.last = "keep"), ncol=ncol(mat))
  # replace all NAs with zeroes again post-ranking
  ranked_mat[is.na(ranked_mat)] <- 0
  
  rownames(ranked_mat) <- rownames(mat)
  colnames(ranked_mat) <- colnames(mat)
  
  matname <- strsplit(basename(matpath), "[.]")
  filename=paste0(getwd(), "/", matname[[1]][1], "_ranked.txt")
  print(paste("Writing ranked matrix to file:", filename))
  write.table(ranked_mat, file = filename, sep = "\t", row.names = TRUE, col.names = NA)
}

rank_mat(matpath)