#!/usr/bin/env Rscript
# Takes a matrix file generated by generate-chipseq-mat.r and converts it to a rank matrix
# (see Computational Methods paper, http://www.cell.com/action/showImagesData?pii=S0092-8674%2812%2901123-3 ) 

args <- commandArgs(trailingOnly=TRUE)
matpath <- paste0(getwd(), "/", as.character(args[1])) # assumes Unix
print(paste("Looking for matrix at:", matpath))

# check arguments for validity
if(length(args) != 1 || !file.exists(matpath)) {
  print("Incorrect or missing argument. File may not exist.")
  print("Usage: rank-mat.R <relative matrix filepath>")
  stop()
}

# applies rank function to matrix <matname> and writes it into the same directory as the source file
# wrapped in function for possible reuse or automation 
rank_mat <- function(matpath) {
  print("Reading matrix.")
  mat <- as.data.frame(read.table(matpath, sep="\t", header=TRUE))
  rownames(mat) <- mat[, 1]
  mat[, 1] <- NULL
  
  print("Ranking.")
  # replace all zeroes or infinities with NA to exclude them from ranking
  mat[mat == 0] <- NA
  mat[mat == Inf] <- NA
  # apply rank to absolute value of confidence scores
  ranked_mat <- matrix(rank(abs(mat), na.last = "keep"), ncol=ncol(mat))
  # replace all NAs with zeroes again post-ranking
  ranked_mat[is.na(ranked_mat)] <- 0
  
  rownames(ranked_mat) <- rownames(mat)
  colnames(ranked_mat) <- colnames(mat)
  
  matname <- strsplit(basename(matpath), "[.]")
  filename=paste0(dirname(matpath), "/", matname[[1]][1], "_ranked.txt")
  print(paste("Writing ranked matrix to file:", filename))
  write.table(ranked_mat, file = filename, sep = "\t", row.names = TRUE, col.names = NA)
}

rank_mat(matpath)