#!/usr/bin/env Rscript
# Takes a matrix file generated by generate-chipseq-mat.r and converts it to a rank matrix

#setwd("/home/chrisk/Documents/uni/thesis/suppl/data/chipseq")

args <- commandArgs(trailingOnly=TRUE)
matname <- as.character(args[1])

if(matname == "") {
  print("Incorrect or missing argument.")
  print("Usage: script.R <matrix-file>")
  stop()
}

mat <- as.data.frame(read.table(matname, sep="\t", header=TRUE))
rownames(mat) <- mat[, 1]
mat[, 1] <- NULL

ranked_mat <- matrix(rank(mat, ties='min', na.last = TRUE), ncol=ncol(mat))
rownames(ranked_mat) <- rownames(mat)
colnames(ranked_mat) <- colnames(mat)

print(mat[1:10,])
print(ranked_mat[1:10,])

filename=paste0(basename(matname), "_ranked.txt")
write.table(ranked_mat, file = filename, sep = "\t", row.names = TRUE, col.names = NA)